print("MD \"Asikur\" Rahaman")
print('I\'m Asikur')
print("A for apple \nB for Ball")
print("this is backslash \\")
print("this is double backslash \\\\")
print("Name\t Asikur")
print("this is backsll\bash \\")